"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#abb2bf)\
[ 🕀 ](bg:#abb2bf fg:#1e2127)\
[](bg:#61afef fg:#abb2bf)\
$directory\
[](fg:#61afef bg:#3e4451)\
$git_branch\
$git_status\
[](fg:#3e4451 bg:#2c313a)\
$nodejs\
$bun\
$rust\
$golang\
$php\
[](fg:#2c313a bg:#21252b)\
$time\
[ ](fg:#21252b)\
\n$character"""

[directory]
style = "fg:#1e2127 bg:#61afef"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#3e4451"
format = '[[ $symbol $branch ](fg:#61afef bg:#3e4451)]($style)'

[git_status]
style = "bg:#3e4451"
format = '[[($all_status$ahead_behind )](fg:#61afef bg:#3e4451)]($style)'

[nodejs]
symbol = ""
style = "bg:#2c313a"
format = '[[ $symbol ($version) ](fg:#61afef bg:#2c313a)]($style)'

[bun]
symbol = ""
style = "bg:#2c313a"
format = '[[ $symbol ($version) ](fg:#61afef bg:#2c313a)]($style)'

[rust]
symbol = ""
style = "bg:#2c313a"
format = '[[ $symbol ($version) ](fg:#61afef bg:#2c313a)]($style)'

[golang]
symbol = ""
style = "bg:#2c313a"
format = '[[ $symbol ($version) ](fg:#61afef bg:#2c313a)]($style)'

[php]
symbol = ""
style = "bg:#2c313a"
format = '[[ $symbol ($version) ](fg:#61afef bg:#2c313a)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#21252b"
format = '[[  $time ](fg:#828997 bg:#21252b)]($style)'
